# This is the main configuration file for your Quarto website.
project:
  type: website
  output-dir: docs

website:
  title: "Michelle Hoda Wilkerson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
#      - href: projects.qmd -- working on it
#        text: Projects 
#      - href: teaching.qmd -- do it later (listing)
#        text: Teaching
#      - href: Resources.qmd -- do it later (listing)
#        text: Resources
        
    right:
      - icon: github
        href: "https://github.com/michellehoda"
      - icon: building
        href: "https://bse.berkeley.edu/michelle-hoda-wilkerson"
      - icon: house-heart
        href: "https://corelab.berkeley.edu"

# Bibliography settings
#bibliography: references.bib
bibliography: references.bib
csl: apa-cv.csl
suppress-bibliography: true
link-citations: false
citations-hover: false

# Appearance settings
format:
  html:
    theme: journal  # I like the orangey pink
    mainfont: "Lora"  # A readable serif font for the main text
    css: "styles.css" # You can add a styles.css file for custom tweaks
    toc: true
    linestretch: 1.3
    fontsize: 12pt